### ISSUE TITLE
Can't get a good build yet

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Plugins#1]
I don't have C++ for VS2010 so I'm trying to build with VS2013. PluginHelpers is returning a lot of "unresolved token" errors. Nothing else builds because they're dependent on that.

**Comment by abstractspoon** [comment]
Yeah sorry. That's a work in progress. Just need to implement some CTaskList functions. Or you could comment out the problem definitions in the header.

**Comment by abstractspoon** [comment]
Build is fixed now. I hadn't implemented some methods in CTaskList.

**Comment by TonyGravagno** [comment]
Downloaded current release and was able to build. Closing this ticket.
